"""
Pet store product catalog with ~30 products across dog, cat, bird, fish, small_animal.
"""

CATALOG = [
    # --- DOG: Dry Skin / Coat ---
    {
        "id": "DOG-OMEGA-001",
        "name": "OmegaCoat Salmon Oil",
        "category": "dog",
        "tags": ["dry_skin", "coat", "omega3", "itching", "supplement"],
        "price": 18.99,
        "aisle": "3B",
        "brand": "NaturePaws",
        "description": "Wild-caught salmon oil rich in EPA/DHA omega-3 fatty acids for skin and coat health.",
        "why_good_for": ["dry skin", "dull coat", "itching", "inflammation"],
        "in_stock": True,
    },
    {
        "id": "DOG-SHAMP-002",
        "name": "SootheSkin Oatmeal Shampoo",
        "category": "dog",
        "tags": ["dry_skin", "itching", "coat", "oatmeal", "grooming"],
        "price": 12.49,
        "aisle": "3C",
        "brand": "PurePet",
        "description": "Colloidal oatmeal shampoo that moisturizes and relieves dry, flaky skin.",
        "why_good_for": ["dry skin", "flaky skin", "itching", "sensitive skin"],
        "in_stock": True,
    },
    {
        "id": "DOG-COAT-003",
        "name": "BioCoat Coconut Conditioner",
        "category": "dog",
        "tags": ["dry_skin", "coat", "conditioning", "moisturizing", "grooming"],
        "price": 14.99,
        "aisle": "3C",
        "brand": "NaturePaws",
        "description": "Deep-conditioning coconut oil treatment that restores shine and softness to dry coats.",
        "why_good_for": ["dry coat", "brittle fur", "dry skin", "dull coat"],
        "in_stock": True,
    },
    # --- DOG: Won't Eat / Appetite ---
    {
        "id": "DOG-TOPPR-004",
        "name": "TastyBite Chicken Gravy Topper",
        "category": "dog",
        "tags": ["picky_eater", "appetite", "topper", "chicken", "food"],
        "price": 9.99,
        "aisle": "2A",
        "brand": "ChompMaster",
        "description": "Savory chicken broth and gravy meal topper to entice picky or low-appetite dogs.",
        "why_good_for": ["won't eat", "picky eater", "appetite stimulation", "food boredom"],
        "in_stock": True,
    },
    {
        "id": "DOG-FOOD-005",
        "name": "WildHarvest Grain-Free Beef Formula",
        "category": "dog",
        "tags": ["picky_eater", "grain_free", "beef", "dry_food", "appetite"],
        "price": 44.99,
        "aisle": "1A",
        "brand": "WildHarvest",
        "description": "High-protein grain-free dry kibble made with real beef as the first ingredient.",
        "why_good_for": ["won't eat", "picky eater", "grain sensitivity", "high protein diet"],
        "in_stock": True,
    },
    {
        "id": "DOG-APPET-006",
        "name": "FeastStimulus Appetite Supplement",
        "category": "dog",
        "tags": ["appetite", "supplement", "picky_eater", "digestive", "health"],
        "price": 22.50,
        "aisle": "3A",
        "brand": "VetWellness",
        "description": "Probiotic and digestive enzyme blend to improve appetite and nutrient absorption.",
        "why_good_for": ["won't eat", "digestive issues", "appetite stimulation", "nutrient absorption"],
        "in_stock": True,
    },
    # --- DOG: Anxiety ---
    {
        "id": "DOG-CALM-007",
        "name": "CalmPaws Lavender Chews",
        "category": "dog",
        "tags": ["anxiety", "calming", "chews", "lavender", "stress"],
        "price": 24.99,
        "aisle": "4A",
        "brand": "ZenPet",
        "description": "Soft chews with lavender, chamomile, and L-theanine to reduce stress and anxiety.",
        "why_good_for": ["anxiety", "stress", "thunderstorm fear", "separation anxiety", "travel stress"],
        "in_stock": True,
    },
    {
        "id": "DOG-WRAP-008",
        "name": "ThunderShield Anxiety Wrap",
        "category": "dog",
        "tags": ["anxiety", "stress", "thunderstorm", "compression", "wearable"],
        "price": 39.95,
        "aisle": "5B",
        "brand": "CalmCritter",
        "description": "Gentle pressure wrap that calms dogs during storms, fireworks, and separation anxiety.",
        "why_good_for": ["anxiety", "thunderstorm fear", "fireworks", "separation anxiety"],
        "in_stock": True,
    },
    {
        "id": "DOG-DIFF-009",
        "name": "SereneSpace Calming Diffuser",
        "category": "dog",
        "tags": ["anxiety", "calming", "diffuser", "pheromone", "stress"],
        "price": 29.99,
        "aisle": "4B",
        "brand": "ZenPet",
        "description": "Plug-in pheromone diffuser that mimics natural dog-appeasing pheromones to reduce anxiety.",
        "why_good_for": ["anxiety", "stress", "new environment", "separation anxiety", "aggression"],
        "in_stock": True,
    },
    # --- DOG: Itchy Paws ---
    {
        "id": "DOG-PAW-010",
        "name": "PawSoothe Balm",
        "category": "dog",
        "tags": ["itchy_paws", "paw_care", "balm", "moisturizing", "paws"],
        "price": 11.99,
        "aisle": "3D",
        "brand": "PurePet",
        "description": "Beeswax and shea butter balm to soothe cracked, dry, and itchy paws.",
        "why_good_for": ["itchy paws", "cracked paws", "dry paws", "paw irritation"],
        "in_stock": True,
    },
    {
        "id": "DOG-PAWW-011",
        "name": "AquaPaw Paw Wash Spritz",
        "category": "dog",
        "tags": ["itchy_paws", "paw_care", "cleaning", "allergen", "spray"],
        "price": 13.50,
        "aisle": "3D",
        "brand": "NaturePaws",
        "description": "Gentle rinse-free paw spray that removes allergens and soothes irritated paws after walks.",
        "why_good_for": ["itchy paws", "environmental allergies", "paw irritation", "allergen removal"],
        "in_stock": True,
    },
    # --- DOG: Puppy Training ---
    {
        "id": "DOG-TRAIN-012",
        "name": "PuppyPro Training Treats",
        "category": "dog",
        "tags": ["puppy", "training", "treats", "reward", "small_bite"],
        "price": 8.99,
        "aisle": "2C",
        "brand": "ChompMaster",
        "description": "Tiny soft training treats perfect for positive reinforcement puppy training sessions.",
        "why_good_for": ["puppy training", "positive reinforcement", "obedience training", "trick training"],
        "in_stock": True,
    },
    {
        "id": "DOG-CLKR-013",
        "name": "ClickStart Training Clicker",
        "category": "dog",
        "tags": ["puppy", "training", "clicker", "obedience", "behavior"],
        "price": 5.49,
        "aisle": "5A",
        "brand": "TrainRight",
        "description": "Ergonomic clicker with wrist strap for precise positive reinforcement training.",
        "why_good_for": ["puppy training", "obedience training", "behavior shaping", "trick training"],
        "in_stock": True,
    },
    # --- CAT: Won't Eat / Appetite ---
    {
        "id": "CAT-TOPPR-014",
        "name": "PurrFeast Tuna Topper",
        "category": "cat",
        "tags": ["picky_eater", "appetite", "topper", "tuna", "food"],
        "price": 7.99,
        "aisle": "2B",
        "brand": "WhiskerFoods",
        "description": "Real tuna flakes meal topper to entice finicky cats and boost appetite.",
        "why_good_for": ["won't eat", "picky eater", "appetite stimulation", "food boredom"],
        "in_stock": True,
    },
    {
        "id": "CAT-FOOD-015",
        "name": "WetNibble Salmon Pate",
        "category": "cat",
        "tags": ["picky_eater", "wet_food", "salmon", "appetite", "food"],
        "price": 18.99,
        "aisle": "1B",
        "brand": "WhiskerFoods",
        "description": "Premium grain-free salmon pate wet food with high moisture content for hydration.",
        "why_good_for": ["won't eat", "picky eater", "hydration", "urinary health"],
        "in_stock": True,
    },
    {
        "id": "CAT-APPET-016",
        "name": "KittyKick Appetite Booster",
        "category": "cat",
        "tags": ["appetite", "supplement", "picky_eater", "vitamin", "health"],
        "price": 19.99,
        "aisle": "3A",
        "brand": "VetWellness",
        "description": "B-vitamin and zinc supplement drops that safely stimulate appetite in cats.",
        "why_good_for": ["won't eat", "appetite stimulation", "vitamin deficiency", "recovery support"],
        "in_stock": True,
    },
    # --- CAT: Scratching Furniture ---
    {
        "id": "CAT-SCRTCH-017",
        "name": "ScratchGuard Deterrent Spray",
        "category": "cat",
        "tags": ["scratching", "furniture", "deterrent", "spray", "behavior"],
        "price": 10.99,
        "aisle": "4C",
        "brand": "CalmCritter",
        "description": "Citrus-scented spray that safely deters cats from scratching furniture and carpets.",
        "why_good_for": ["scratching furniture", "behavior correction", "furniture protection"],
        "in_stock": True,
    },
    {
        "id": "CAT-POST-018",
        "name": "Sisal Supreme Scratching Post",
        "category": "cat",
        "tags": ["scratching", "post", "sisal", "furniture_alternative", "enrichment"],
        "price": 34.95,
        "aisle": "5C",
        "brand": "PurePet",
        "description": "Tall, sturdy sisal rope scratching post to redirect destructive scratching behavior.",
        "why_good_for": ["scratching furniture", "nail health", "enrichment", "behavior redirection"],
        "in_stock": True,
    },
    # --- CAT: Hairball ---
    {
        "id": "CAT-HAIR-019",
        "name": "HairballAway Malt Paste",
        "category": "cat",
        "tags": ["hairball", "digestive", "malt", "paste", "supplement"],
        "price": 9.49,
        "aisle": "3A",
        "brand": "VetWellness",
        "description": "Malt-flavored paste that lubricates the digestive tract to ease hairball passage.",
        "why_good_for": ["hairballs", "digestive blockage", "vomiting", "grooming side effects"],
        "in_stock": True,
    },
    {
        "id": "CAT-HFOOD-020",
        "name": "LintFree Hairball Control Kibble",
        "category": "cat",
        "tags": ["hairball", "fiber", "dry_food", "digestive", "coat"],
        "price": 27.99,
        "aisle": "1B",
        "brand": "WhiskerFoods",
        "description": "High-fiber dry cat food formulated to reduce hairball formation and support digestion.",
        "why_good_for": ["hairballs", "digestive health", "coat shedding", "fiber intake"],
        "in_stock": True,
    },
    # --- FISH: Cloudy Water ---
    {
        "id": "FISH-CLEAR-021",
        "name": "AquaClear Water Clarifier",
        "category": "fish",
        "tags": ["cloudy_water", "water_quality", "clarifier", "aquarium", "treatment"],
        "price": 8.99,
        "aisle": "6A",
        "brand": "AquaLife",
        "description": "Fast-acting clarifier that clumps fine particles for easy filter removal in freshwater tanks.",
        "why_good_for": ["cloudy water", "water clarity", "bacterial bloom", "particle removal"],
        "in_stock": True,
    },
    {
        "id": "FISH-CYCL-022",
        "name": "BioStart Beneficial Bacteria",
        "category": "fish",
        "tags": ["cloudy_water", "water_quality", "bacteria", "cycling", "aquarium"],
        "price": 13.99,
        "aisle": "6A",
        "brand": "AquaLife",
        "description": "Live beneficial bacteria formula to establish biological filtration and clear cloudy water.",
        "why_good_for": ["cloudy water", "new tank syndrome", "ammonia spike", "nitrogen cycle"],
        "in_stock": True,
    },
    # --- FISH: Ich Treatment ---
    {
        "id": "FISH-ICH-023",
        "name": "IchAway Copper Treatment",
        "category": "fish",
        "tags": ["ich", "parasite", "treatment", "disease", "aquarium"],
        "price": 11.50,
        "aisle": "6B",
        "brand": "AquaLife",
        "description": "Copper-based ich treatment effective against white spot disease in freshwater fish.",
        "why_good_for": ["ich", "white spot disease", "parasite treatment", "fish disease"],
        "in_stock": True,
    },
    # --- SMALL ANIMAL: Bedding ---
    {
        "id": "SMALL-BED-024",
        "name": "CozyNest Paper Bedding",
        "category": "small_animal",
        "tags": ["bedding", "paper", "absorbent", "odor_control", "comfortable"],
        "price": 16.99,
        "aisle": "7A",
        "brand": "BurrowBest",
        "description": "Ultra-soft paper bedding with 99% dust-free formula and superior odor control.",
        "why_good_for": ["bedding", "odor control", "comfort", "burrowing", "respiratory health"],
        "in_stock": True,
    },
    # --- SMALL ANIMAL: Food ---
    {
        "id": "SMALL-FOOD-025",
        "name": "HamsterHarvest Premium Mix",
        "category": "small_animal",
        "tags": ["food", "hamster", "gerbil", "seed_mix", "nutrition"],
        "price": 12.99,
        "aisle": "7B",
        "brand": "BurrowBest",
        "description": "Nutritionally balanced seed, grain, and vegetable mix for hamsters and gerbils.",
        "why_good_for": ["nutrition", "balanced diet", "foraging enrichment", "dental health"],
        "in_stock": True,
    },
    # --- BIRD: Feather Health ---
    {
        "id": "BIRD-FEATH-026",
        "name": "PlumePlus Feather Supplement",
        "category": "bird",
        "tags": ["feather_health", "supplement", "molting", "vitamin", "plumage"],
        "price": 17.49,
        "aisle": "8A",
        "brand": "AvianCare",
        "description": "Vitamin and amino acid supplement added to water to support healthy feather growth during molting.",
        "why_good_for": ["feather health", "molting support", "plucking prevention", "bright plumage"],
        "in_stock": True,
    },
    # --- BIRD: Food ---
    {
        "id": "BIRD-FOOD-027",
        "name": "TropicBlend Parrot Pellets",
        "category": "bird",
        "tags": ["food", "parrot", "pellets", "nutrition", "balanced"],
        "price": 23.99,
        "aisle": "8B",
        "brand": "AvianCare",
        "description": "Nutritionally complete fruit-flavored pellets formulated for parrots and large hookbills.",
        "why_good_for": ["nutrition", "balanced diet", "vitamin intake", "digestive health"],
        "in_stock": True,
    },
    # --- Additional Products for Coverage ---
    {
        "id": "DOG-PRTZ-028",
        "name": "ProBelly Probiotic Chews",
        "category": "dog",
        "tags": ["digestive", "probiotic", "supplement", "picky_eater", "appetite"],
        "price": 21.99,
        "aisle": "3A",
        "brand": "VetWellness",
        "description": "Daily probiotic soft chews that support gut health and may improve appetite in picky dogs.",
        "why_good_for": ["digestive issues", "won't eat", "loose stool", "gut health"],
        "in_stock": True,
    },
    {
        "id": "CAT-CALM-029",
        "name": "FeliCalm Pheromone Collar",
        "category": "cat",
        "tags": ["anxiety", "calming", "pheromone", "collar", "stress"],
        "price": 19.95,
        "aisle": "4C",
        "brand": "CalmCritter",
        "description": "30-day pheromone-infused collar that reduces stress and anxiety in cats.",
        "why_good_for": ["anxiety", "stress", "new environment", "multi-cat household tension"],
        "in_stock": True,
    },
    {
        "id": "FISH-COND-030",
        "name": "AquaSafe Water Conditioner",
        "category": "fish",
        "tags": ["water_quality", "conditioner", "dechlorinator", "aquarium", "safety"],
        "price": 7.49,
        "aisle": "6A",
        "brand": "AquaLife",
        "description": "Instantly neutralizes chlorine, chloramines, and heavy metals to make tap water safe for fish.",
        "why_good_for": ["cloudy water", "new tank setup", "water changes", "fish health"],
        "in_stock": True,
    },
]


def search_products(query_tags: list, category: str = None, top_n: int = 5) -> list:
    """Score products by tag overlap and return top_n sorted by score."""
    results = []
    for p in CATALOG:
        if not p.get("in_stock"):
            continue
        if category and category != "any" and p["category"] != category:
            continue
        score = 0
        combined = p["tags"] + [w for phrase in p["why_good_for"] for w in phrase.split()]
        combined_lower = [t.lower() for t in combined]
        for tag in query_tags:
            if tag.lower() in combined_lower:
                score += 1
        if score > 0:
            results.append((score, p))
    results.sort(key=lambda x: x[0], reverse=True)
    return [p for _, p in results[:top_n]]


def get_product_by_id(product_id: str) -> dict:
    """Return a product dict by ID, or None if not found."""
    for p in CATALOG:
        if p["id"] == product_id:
            return p
    return None
