#
# Copyright (c) 2024–2025, Daily
#
# SPDX-License-Identifier: BSD 2-Clause License
#

"""pipecat-esp32-smallwebrtc-demo - Pipecat Voice Agent

This bot uses a cascade pipeline: Speech-to-Text → LLM → Text-to-Speech

Generated by Pipecat CLI

Required AI services:
- Deepgram (Speech-to-Text via Flux) and Deepgram (Text-to-Speech)
- Anthropic (LLM)

Run the bot using::

    uv run bot.py
"""


import sys

from pipecat.runner.types import RunnerArguments
from pipecat.transports.base_transport import BaseTransport
from pipecat.frames.frames import LLMRunFrame
from dotenv import load_dotenv
from pipecat.transports.smallwebrtc.connection import SmallWebRTCConnection
from pipecat.transports.smallwebrtc.transport import SmallWebRTCTransport
from pipecat.transports.base_transport import TransportParams
from pipecat.pipeline.task import PipelineParams, PipelineTask
from pipecat.processors.aggregators.llm_response_universal import (
    LLMContextAggregatorPair,
    LLMUserAggregatorParams,
)
from loguru import logger
from pipecat.processors.frameworks.rtvi import RTVIObserver, RTVIProcessor
import os
from pipecat.services.anthropic.llm import AnthropicLLMService
from pipecat.services.deepgram.flux.stt import DeepgramFluxSTTService
from pipecat.services.deepgram.tts import DeepgramTTSService
from pipecat.runner.types import SmallWebRTCRunnerArguments
from pipecat.pipeline.pipeline import Pipeline
from pipecat.pipeline.runner import PipelineRunner
from pipecat.processors.aggregators.llm_context import LLMContext
from pipecat.turns.user_turn_strategies import ExternalUserTurnStrategies



load_dotenv(override=True)


def _patch_runner_bind_host() -> None:
    """Bind locally to all interfaces in ESP32 mode while preserving the advertised IP.

    Pipecat uses ``--host`` both for ESP32 SDP munging and for the Uvicorn bind
    address. Browsers suppress ``getUserMedia`` on plain HTTP IP origins, so for
    local testing we bind to ``0.0.0.0`` and steer the browser to ``localhost``.
    """
    from pipecat.runner import run as runner_run

    original_uvicorn_run = runner_run.uvicorn.run

    def patched_uvicorn_run(app, host, port, *args, **kwargs):
        if "--esp32" not in sys.argv or host in {"localhost", "127.0.0.1", "0.0.0.0"}:
            return original_uvicorn_run(app, host=host, port=port, *args, **kwargs)

        print(f"   → For this machine, open http://localhost:{port}/client/")
        print(f"   → ESP32 signalling still uses http://{host}:{port}")
        print()

        return original_uvicorn_run(app, host="0.0.0.0", port=port, *args, **kwargs)

    runner_run.uvicorn.run = patched_uvicorn_run

async def run_bot(transport: BaseTransport):
    """Main bot logic."""
    logger.info("Starting bot")
    flux_model = os.getenv("DEEPGRAM_STT_MODEL", "flux-general-en")
    if flux_model != "flux-general-en":
        raise ValueError(
            "Deepgram Flux requires DEEPGRAM_STT_MODEL=flux-general-en; "
            f"got {flux_model!r}"
        )

    # Speech-to-Text service
    stt = DeepgramFluxSTTService(
            api_key=os.getenv("DEEPGRAM_API_KEY"),
            settings=DeepgramFluxSTTService.Settings(
                model=flux_model
            ),
        )

    # Text-to-Speech service
    tts = DeepgramTTSService(
            api_key=os.getenv("DEEPGRAM_API_KEY"),
            settings=DeepgramTTSService.Settings(
                voice=os.getenv("DEEPGRAM_TTS_VOICE", "aura-2-helena-en")
            ),
        )


    # LLM service
    llm = AnthropicLLMService(
            api_key=os.getenv("ANTHROPIC_API_KEY"),
            model=os.getenv("ANTHROPIC_MODEL", "claude-3-5-haiku-latest")
        )



    messages = [
        {
            "role": "system",
            "content": "You are a friendly AI assistant. Respond naturally and keep your answers conversational.",
        },
    ]

    context = LLMContext(messages)
    context_aggregator = LLMContextAggregatorPair(
        context,
        user_params=LLMUserAggregatorParams(
            user_turn_strategies=ExternalUserTurnStrategies()
        ),
    )


    

    rtvi = RTVIProcessor()


    # Pipeline - assembled from reusable components
    pipeline = Pipeline([
        transport.input(),

        rtvi,

        stt,

        
        context_aggregator.user(),

        llm,

        tts,

        
        transport.output(),

        
        
        context_aggregator.assistant(),

    ])


    task = PipelineTask(
        pipeline,
        params=PipelineParams(
            enable_metrics=True,
            enable_usage_metrics=True,
        ),
        observers=[
            RTVIObserver(rtvi),
        ],
    )

    @rtvi.event_handler("on_client_ready")
    async def on_client_ready(rtvi):
        await rtvi.set_bot_ready()
        # Kick off the conversation
        await task.queue_frames([LLMRunFrame()])

    @transport.event_handler("on_client_connected")
    async def on_client_connected(transport, client):
        logger.info("Client connected")

    @transport.event_handler("on_client_disconnected")
    async def on_client_disconnected(transport, client):
        logger.info("Client disconnected")
        await task.cancel()




    runner = PipelineRunner(handle_sigint=False)

    await runner.run(task)


async def bot(runner_args: RunnerArguments):
    """Main bot entry point."""
    if isinstance(runner_args, SmallWebRTCRunnerArguments):
        logger.info("Received SmallWebRTC connection")


    transport = None

    match runner_args:
        case SmallWebRTCRunnerArguments():
            webrtc_connection: SmallWebRTCConnection = runner_args.webrtc_connection

            transport = SmallWebRTCTransport(
                webrtc_connection=webrtc_connection,
                params=TransportParams(
                    audio_in_enabled=True,
                    audio_out_enabled=True,
                ),
            )
        case _:
            logger.error(f"Unsupported runner arguments type: {type(runner_args)}")
            return

    try:
        await run_bot(transport)
    finally:
        if isinstance(runner_args, SmallWebRTCRunnerArguments):
            logger.info("Cleaning up SmallWebRTC resources")


if __name__ == "__main__":
    from pipecat.runner.run import main

    _patch_runner_bind_host()
    main()
