#
# Copyright (c) 2024–2025, Daily
#
# SPDX-License-Identifier: BSD 2-Clause License
#

"""pipecat-esp32-smallwebrtc-demo - Pipecat Voice Agent

This bot uses a cascade pipeline: Speech-to-Text → LLM → Text-to-Speech

Generated by Pipecat CLI

Required AI services:
- Deepgram (Speech-to-Text via Flux) and Deepgram (Text-to-Speech)
- Anthropic (LLM)

Run the bot using::

    uv run bot.py
"""

import os
import sys
from typing import Literal

import httpx
import pipecat.processors.frameworks.rtvi.models as RTVI
from dotenv import load_dotenv
from fastapi import FastAPI
from loguru import logger
from pipecat.adapters.schemas.function_schema import FunctionSchema
from pipecat.adapters.schemas.tools_schema import ToolsSchema
from pipecat.frames.frames import LLMRunFrame
from pipecat.pipeline.pipeline import Pipeline
from pipecat.pipeline.runner import PipelineRunner
from pipecat.pipeline.task import PipelineParams, PipelineTask
from pipecat.processors.aggregators.llm_context import LLMContext
from pipecat.processors.aggregators.llm_response_universal import (
    LLMContextAggregatorPair,
    LLMUserAggregatorParams,
)
from pipecat.processors.frameworks.rtvi import RTVIObserver, RTVIProcessor
from pipecat.runner.types import RunnerArguments, SmallWebRTCRunnerArguments
from pipecat.services.anthropic.llm import AnthropicLLMService, AnthropicLLMSettings
from pipecat.services.deepgram.flux.stt import DeepgramFluxSTTService
from pipecat.services.deepgram.tts import DeepgramTTSService
from pipecat.services.llm_service import FunctionCallParams
from pipecat.transports.base_transport import BaseTransport, TransportParams
from pipecat.transports.smallwebrtc.connection import SmallWebRTCConnection
from pipecat.transports.smallwebrtc.transport import SmallWebRTCTransport
from pipecat.turns.user_turn_strategies import ExternalUserTurnStrategies
from pydantic import BaseModel

from kiosk import (
    LocalInventoryAdapter,
    LocalMapService,
    MapRegistry,
    SessionState,
    install_map_routes,
)

load_dotenv(override=True)

MAP_REGISTRY = MapRegistry()

# URL of the Next.js backend (single source of truth for business logic)
NEXTJS_URL = os.getenv("NEXTJS_URL", "http://localhost:3000")

SYSTEM_PROMPT = """You are Amy, a voice help kiosk for a pet store.
Keep every reply brief and conversational because customers are standing at the kiosk.
You speak out loud, so respond in plain natural speech only.
Do not use markdown, bullet points, numbered lists, emojis, symbols, or screen-oriented formatting.
Do not say things like "I am showing a list below" or refer to on-screen text unless you are explicitly talking about the QR code.
Your job is to help shoppers find products and build a shopping list.
Always use the available tools for product lookup and shopping-list actions.
Never invent product availability or locations.
If find_items returns multiple matches, ask the shopper a short follow-up question and wait.
Only call add_item after the shopper confirms the product is correct.
When the shopper says they are done, wants their list, or asks for directions, call generate_plan.
Mention aisle and shelf only when it helps the shopper choose the right item."""

TOOLS = ToolsSchema(
    [
        FunctionSchema(
            name="find_items",
            description="Search the pet store inventory for the item the shopper wants.",
            properties={
                "query": {
                    "type": "string",
                    "description": "What the shopper is looking for, in natural language.",
                }
            },
            required=["query"],
        ),
        FunctionSchema(
            name="add_item",
            description="Add a confirmed item to the current shopper's list. Auto-checks compatibility.",
            properties={
                "item_id": {
                    "type": "string",
                    "description": "The item_id returned by find_items for the confirmed product.",
                },
                "quantity": {
                    "type": "integer",
                    "description": "How many of this item to add. Defaults to 1.",
                    "minimum": 1,
                },
            },
            required=["item_id"],
        ),
        FunctionSchema(
            name="remove_item",
            description="Remove an item from the current shopper's list.",
            properties={
                "item_id": {
                    "type": "string",
                    "description": "The item_id to remove from the shopping list.",
                },
            },
            required=["item_id"],
        ),
        FunctionSchema(
            name="generate_plan",
            description="Create a QR-ready shopping plan with store route for the current session list.",
            properties={
                "title": {
                    "type": "string",
                    "description": "A friendly title for the shopping plan.",
                },
                "summary": {
                    "type": "string",
                    "description": "Brief summary of what was recommended.",
                },
                "proTips": {
                    "type": "array",
                    "items": {"type": "string"},
                    "description": "Helpful care tips for the customer.",
                },
                "petContext": {
                    "type": "string",
                    "description": "Description of the customer's pet situation.",
                },
            },
            required=["title", "summary", "proTips", "petContext"],
        ),
    ]
)


class ShowQRCodeMessage(BaseModel):
    label: Literal["rtvi-ai"] = RTVI.MESSAGE_LABEL
    type: Literal["show-qr-code"] = "show-qr-code"
    data: dict[str, str]


class HideQRCodeMessage(BaseModel):
    label: Literal["rtvi-ai"] = RTVI.MESSAGE_LABEL
    type: Literal["hide-qr-code"] = "hide-qr-code"


def _public_base_url() -> str:
    configured = os.getenv("KIOSK_PUBLIC_BASE_URL")
    if configured:
        return configured.rstrip("/")

    from pipecat.runner import run as runner_run

    return f"http://{runner_run.RUNNER_HOST}:{runner_run.RUNNER_PORT}"


def _patch_runner_bind_host() -> None:
    """Bind locally to all interfaces in ESP32 mode while preserving the advertised IP.

    Pipecat uses ``--host`` both for ESP32 SDP munging and for the Uvicorn bind
    address. Browsers suppress ``getUserMedia`` on plain HTTP IP origins, so for
    local testing we bind to ``0.0.0.0`` and steer the browser to ``localhost``.
    """
    from pipecat.runner import run as runner_run

    original_uvicorn_run = runner_run.uvicorn.run

    def patched_uvicorn_run(app, host, port, *args, **kwargs):
        if "--esp32" not in sys.argv or host in {"localhost", "127.0.0.1", "0.0.0.0"}:
            return original_uvicorn_run(app, host=host, port=port, *args, **kwargs)

        print(f"   → For this machine, open http://localhost:{port}/client/")
        print(f"   → ESP32 signalling still uses http://{host}:{port}")
        print()

        return original_uvicorn_run(app, host="0.0.0.0", port=port, *args, **kwargs)

    runner_run.uvicorn.run = patched_uvicorn_run


def _patch_runner_app_routes() -> None:
    from pipecat.runner import run as runner_run

    if getattr(runner_run, "_kiosk_routes_patched", False):
        return

    original_create_server_app = runner_run._create_server_app

    def patched_create_server_app(args) -> FastAPI:
        app = original_create_server_app(args)
        install_map_routes(app, MAP_REGISTRY)
        return app

    runner_run._create_server_app = patched_create_server_app
    runner_run._kiosk_routes_patched = True


# Shared HTTP client for calling Next.js API routes
_http_client = httpx.Client(base_url=NEXTJS_URL, timeout=15.0)


def _call_nextjs_tool(tool_name: str, session_id: str, **kwargs) -> dict:
    """Call a Next.js tool API endpoint and return the JSON response."""
    payload = {"sessionId": session_id, **kwargs}
    resp = _http_client.post(f"/api/tools/{tool_name}", json=payload)
    resp.raise_for_status()
    return resp.json()


async def run_bot(transport: BaseTransport):
    """Main bot logic."""
    logger.info("Starting bot")
    # Keep local inventory/map as fallback for legacy map HTML routes
    inventory = LocalInventoryAdapter()
    map_service = LocalMapService()
    session = SessionState()

    # Once Next.js fails for any tool call, stay local for the rest of
    # the session to avoid split state between the two stores.
    nextjs_degraded = False

    # Generate a session ID to share state with Next.js
    import secrets
    session_id = secrets.token_urlsafe(16)

    flux_model = os.getenv("DEEPGRAM_STT_MODEL", "flux-general-en")
    if flux_model != "flux-general-en":
        raise ValueError(
            "Deepgram Flux requires DEEPGRAM_STT_MODEL=flux-general-en; "
            f"got {flux_model!r}"
        )

    # Speech-to-Text service
    stt = DeepgramFluxSTTService(
        api_key=os.getenv("DEEPGRAM_API_KEY"),
        settings=DeepgramFluxSTTService.Settings(model=flux_model),
    )

    # Text-to-Speech service
    tts = DeepgramTTSService(
        api_key=os.getenv("DEEPGRAM_API_KEY"),
        sample_rate=int(os.getenv("DEEPGRAM_TTS_SAMPLE_RATE", "16000")),
        encoding=os.getenv("DEEPGRAM_TTS_ENCODING", "linear16"),
        settings=DeepgramTTSService.Settings(
            voice=os.getenv("DEEPGRAM_TTS_VOICE", "aura-2-helena-en")
        ),
    )

    # LLM service
    llm = AnthropicLLMService(
        api_key=os.getenv("ANTHROPIC_API_KEY"),
        settings=AnthropicLLMSettings(
            model=os.getenv("ANTHROPIC_MODEL", "claude-3-5-haiku-latest")
        ),
    )

    rtvi = RTVIProcessor()

    def _use_local(tool: str, err: Exception | None = None) -> None:
        """Mark session as degraded so all future calls stay local."""
        nonlocal nextjs_degraded
        if not nextjs_degraded:
            reason = f" ({err})" if err else ""
            logger.warning(f"Switching to local-only mode for this session{reason}")
        nextjs_degraded = True

    def _find_items_local(query: str) -> dict:
        matches = inventory.find_item(query)
        payload: dict = {
            "status": "ok" if matches else "not_found",
            "query": query,
            "matches": [item.to_public_dict() for item in matches],
        }
        if not matches:
            payload["message"] = f"No close matches found for '{query}'."
        return payload

    def _add_item_local(item_id: str, quantity: int) -> dict:
        item = inventory.get_item(item_id)
        if not item:
            return {
                "status": "error",
                "message": f"Unknown item_id '{item_id}'. Use id values returned by find_items.",
            }
        entry = session.add_item(item, quantity=quantity)
        return {
            "status": "ok",
            "added_item": entry.to_public_dict(),
            "list_count": session.item_count(),
            "list_items": [saved.to_public_dict() for saved in session.list_items()],
        }

    def _remove_item_local(item_id: str) -> dict:
        if item_id in session.shopping_list:
            removed = session.shopping_list.pop(item_id)
            return {
                "status": "ok",
                "removed_item": {"id": item_id, "name": removed.item.name},
                "list_count": session.item_count(),
            }
        return {"status": "error", "message": f"Item '{item_id}' not found in the shopping list."}

    def _generate_plan_local(entries: list) -> dict | None:
        if not entries:
            return None
        record = MAP_REGISTRY.create(entries, map_service)
        map_url = f"{_public_base_url()}/maps/{record.token}"
        return {
            "status": "ok",
            "map_url": map_url,
            "qr_url": map_url,
            "summary": record.summary,
            "items": record.items,
        }

    # ---- Tool handlers --------------------------------------------------

    async def handle_find_items(params: FunctionCallParams) -> None:
        query = str(params.arguments.get("query", "")).strip()
        if nextjs_degraded:
            await params.result_callback(_find_items_local(query))
            return
        try:
            result = _call_nextjs_tool("find_items", session_id, query=query)
            await params.result_callback(result)
        except Exception as e:
            _use_local("find_items", e)
            await params.result_callback(_find_items_local(query))

    async def handle_add_item(params: FunctionCallParams) -> None:
        item_id = str(params.arguments.get("item_id", "")).strip()
        quantity = int(params.arguments.get("quantity", 1) or 1)
        if quantity < 1:
            quantity = 1

        if nextjs_degraded:
            await params.result_callback(_add_item_local(item_id, quantity))
            return
        try:
            result = _call_nextjs_tool(
                "add_item", session_id, item_id=item_id, quantity=quantity
            )
            # Surface compatibility warnings/suggestions so voice customers hear them
            extras = []
            for w in result.get("warnings", []):
                extras.append(f"Warning: {w}")
            for s in result.get("suggestions", []):
                extras.append(f"Suggestion: {s}")
            if extras:
                result["voice_notes"] = " ".join(extras)
            await params.result_callback(result)
        except Exception as e:
            _use_local("add_item", e)
            await params.result_callback(_add_item_local(item_id, quantity))

    async def handle_remove_item(params: FunctionCallParams) -> None:
        item_id = str(params.arguments.get("item_id", "")).strip()
        if nextjs_degraded:
            await params.result_callback(_remove_item_local(item_id))
            return
        try:
            result = _call_nextjs_tool("remove_item", session_id, item_id=item_id)
            await params.result_callback(result)
        except Exception as e:
            _use_local("remove_item", e)
            await params.result_callback(_remove_item_local(item_id))

    async def handle_generate_plan(params: FunctionCallParams) -> None:
        nonlocal nextjs_degraded
        title = str(params.arguments.get("title", "Your Shopping Plan"))
        summary = str(params.arguments.get("summary", ""))
        pro_tips = params.arguments.get("proTips", [])
        pet_context = str(params.arguments.get("petContext", ""))

        if nextjs_degraded:
            entries = session.list_items()
            local_result = _generate_plan_local(entries)
            if not local_result:
                await params.result_callback(
                    {"status": "empty", "message": "The shopping list is empty. Add items first."}
                )
                return
            try:
                await rtvi.push_transport_message(
                    ShowQRCodeMessage(data={"url": local_result["map_url"]})
                )
            except Exception as qr_err:
                logger.warning(f"Failed to push QR message: {qr_err}")
            await params.result_callback(local_result)
            return

        try:
            result = _call_nextjs_tool(
                "generate_plan",
                session_id,
                title=title,
                summary=summary,
                proTips=pro_tips,
                petContext=pet_context,
            )
            if result.get("status") == "ok":
                # Build the plan URL pointing to Next.js plan page
                public_url = os.getenv("NEXT_PUBLIC_URL") or os.getenv("NEXTJS_PUBLIC_URL") or NEXTJS_URL
                map_url = f"{public_url.rstrip('/')}/plan/{session_id}"
                try:
                    await rtvi.push_transport_message(
                        ShowQRCodeMessage(data={"url": map_url})
                    )
                except Exception as qr_err:
                    logger.warning(f"Failed to push QR message: {qr_err}")
                result["map_url"] = map_url
                result["qr_url"] = map_url
            await params.result_callback(result)
        except Exception as e:
            _use_local("generate_plan", e)
            entries = session.list_items()
            local_result = _generate_plan_local(entries)
            if not local_result:
                await params.result_callback(
                    {"status": "empty", "message": "The shopping list is empty. Add items first."}
                )
                return
            try:
                await rtvi.push_transport_message(
                    ShowQRCodeMessage(data={"url": local_result["map_url"]})
                )
            except Exception as qr_err:
                logger.warning(f"Failed to push QR message: {qr_err}")
            await params.result_callback(local_result)

    llm.register_function("find_items", handle_find_items)
    llm.register_function("add_item", handle_add_item)
    llm.register_function("remove_item", handle_remove_item)
    llm.register_function("generate_plan", handle_generate_plan)

    messages = [
        {
            "role": "system",
            "content": SYSTEM_PROMPT,
        },
    ]

    context = LLMContext(messages, tools=TOOLS)
    context_aggregator = LLMContextAggregatorPair(
        context,
        user_params=LLMUserAggregatorParams(user_turn_strategies=ExternalUserTurnStrategies()),
    )

    # Pipeline - assembled from reusable components
    pipeline = Pipeline(
        [
            transport.input(),
            rtvi,
            stt,
            context_aggregator.user(),
            llm,
            tts,
            transport.output(),
            context_aggregator.assistant(),
        ]
    )


    task = PipelineTask(
        pipeline,
        params=PipelineParams(
            enable_metrics=True,
            enable_usage_metrics=True,
        ),
        observers=[
            RTVIObserver(rtvi),
        ],
    )

    @rtvi.event_handler("on_client_ready")
    async def on_client_ready(rtvi):
        await rtvi.push_transport_message(HideQRCodeMessage())
        await rtvi.set_bot_ready()
        # Kick off the conversation
        await task.queue_frames([LLMRunFrame()])

    @transport.event_handler("on_client_connected")
    async def on_client_connected(transport, client):
        logger.info("Client connected")

    @transport.event_handler("on_client_disconnected")
    async def on_client_disconnected(transport, client):
        logger.info("Client disconnected")
        await task.cancel()

    runner = PipelineRunner(handle_sigint=False)

    await runner.run(task)


async def bot(runner_args: RunnerArguments):
    """Main bot entry point."""
    if isinstance(runner_args, SmallWebRTCRunnerArguments):
        logger.info("Received SmallWebRTC connection")


    transport = None

    match runner_args:
        case SmallWebRTCRunnerArguments():
            webrtc_connection: SmallWebRTCConnection = runner_args.webrtc_connection

            transport = SmallWebRTCTransport(
                webrtc_connection=webrtc_connection,
                params=TransportParams(
                    audio_in_enabled=True,
                    audio_out_enabled=True,
                ),
            )
        case _:
            logger.error(f"Unsupported runner arguments type: {type(runner_args)}")
            return

    try:
        await run_bot(transport)
    finally:
        if isinstance(runner_args, SmallWebRTCRunnerArguments):
            logger.info("Cleaning up SmallWebRTC resources")


if __name__ == "__main__":
    from pipecat.runner.run import main

    _patch_runner_bind_host()
    _patch_runner_app_routes()
    main()
